name: HerShield
description: "Women Safety SOS App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^4.0.2
  geolocator: ^10.1.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3

  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  http: ^1.2.0

  cupertino_icons: ^1.0.8

  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# ðŸ“± HOME SCREEN APP ICON
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

# ðŸš€ SPLASH SCREEN (APP OPEN LOGO)
flutter_native_splash:
  color: "#2B0038"
  image: assets/icon/app_logo.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_logo.png
